Add item requests
KosmoAV/java-shareit pull request #4
Opened 2024-03-27 21:31 UTC by KosmoAV

first time

2024-04-01 16:29 UTC, Yang-Pi requested changes

2024-04-01 16:29 UTC, Yang-Pi commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                @RequestParam(required = false) Integer from,
Рекомендую добавить значения по-умолчанию для from и size на этом уровне, параметр defaultValue

2024-04-01 16:29 UTC, Yang-Pi commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                @RequestParam(required = false) Integer from,
+ можешь использовать @Positive, чтобы на уровне коннектора отсекать неверные запросы

2024-04-01 16:29 UTC, Yang-Pi commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            page = PageRequest.of(0, Integer.MAX_VALUE);
При текущей реализации размер страницы вполне может быть 2147483647, такой размер ответа просто может 1) не пройти по лимиту памяти 2) застопорить все API

Значением по умолчанию может быть 10 или 50, но не больше 100)

2024-04-01 16:29 UTC, Yang-Pi commented on src/test/java/ru/practicum/shareit/BookingControllerTests.java
> +package ru.practicum.shareit;
Тесты разложи по соответствующим пакетам

2024-04-01 16:29 UTC, Yang-Pi commented on src/test/java/ru/practicum/shareit/CommentRepositoryTests.java
> +        assertThat(commentList, notNullValue());
Используй assert-ы библиотеки junit (org.junit.jupiter.api), тогда не придется добавлять доп зависимость на hamcrest

2024-04-01 17:44 UTC, KosmoAV commented on src/test/java/ru/practicum/shareit/CommentRepositoryTests.java
> +        assertThat(commentList, notNullValue());
Этой библиотекой пользовались на вебинаре.
Считаю нецелесообразным что-то менять.

2024-04-01 17:44 UTC, KosmoAV commented on src/test/java/ru/practicum/shareit/BookingControllerTests.java
> +package ru.practicum.shareit;
Исправил

2024-04-01 17:44 UTC, KosmoAV commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            page = PageRequest.of(0, Integer.MAX_VALUE);
Исправил

2024-04-01 17:44 UTC, KosmoAV commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                @RequestParam(required = false) Integer from,
Исправил

2024-04-02 14:41 UTC, Yang-Pi approved these changes

2024-04-02 15:46 UTC, merged